 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 10:30:37
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1061cdd00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-06 10:30:38,141: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 10:30:38,151: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 10:30:38,151: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 10:30:38,152: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 10:30:39,168: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 10:30:39,168: INFO/MainProcess] mingle: all alone
[2025-01-06 10:30:39,179: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 10:47:45
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x105c19d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-06 10:47:46,104: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 10:47:46,110: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 10:47:46,110: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 10:47:46,112: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 10:47:47,127: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 10:47:47,127: INFO/MainProcess] mingle: all alone
[2025-01-06 10:47:47,136: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 10:57:43
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x10438dd00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-06 10:57:43,918: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 10:57:43,924: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 10:57:43,924: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 10:57:43,925: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 10:57:44,938: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 10:57:44,938: INFO/MainProcess] mingle: all alone
[2025-01-06 10:57:44,948: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.
[2025-01-06 10:59:38,453: INFO/MainProcess] Task explorebg.questions.tasks.send_email_task[c9ca9b74-13bc-4508-acfa-8a4262391701] received
[2025-01-06 10:59:39,176: ERROR/ForkPoolWorker-8] Task explorebg.questions.tasks.send_email_task[c9ca9b74-13bc-4508-acfa-8a4262391701] raised unexpected: SMTPSenderRefused(530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-38a1c828cc8sm47544901f8f.17 - gsmtp', 'explorebg.quiz@outlook.com')
Traceback (most recent call last):
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/explorebg/questions/tasks.py", line 6, in send_email_task
    send_mail(
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/smtplib.py", line 882, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-38a1c828cc8sm47544901f8f.17 - gsmtp', 'explorebg.quiz@outlook.com')

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:14:33
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x104a5dd00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-06 11:14:34,103: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:14:34,107: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:14:34,107: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:14:34,110: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:14:35,125: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:14:35,125: INFO/MainProcess] mingle: all alone
[2025-01-06 11:14:35,133: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:17:16
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x101d39d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 11:17:16,650: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:17:16,655: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:17:16,656: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:17:16,657: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:17:17,668: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:17:17,668: INFO/MainProcess] mingle: all alone
[2025-01-06 11:17:17,677: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.
[2025-01-06 11:17:41,084: INFO/MainProcess] Task explorebg.questions.views.send_email_task[a526fdb1-99f6-480f-ae14-f7f130619af7] received
[2025-01-06 11:17:41,086: WARNING/ForkPoolWorker-8] +++++++++++++++++++++++EMAIL SEND+++++++++++++++++++++++++++
[2025-01-06 11:17:41,619: ERROR/ForkPoolWorker-8] Task explorebg.questions.views.send_email_task[a526fdb1-99f6-480f-ae14-f7f130619af7] raised unexpected: SMTPSenderRefused(530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 5b1f17b1804b1-4365d116d8fsm572848555e9.17 - gsmtp', 'explorebg.quiz@outlook.com')
Traceback (most recent call last):
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/explorebg/questions/views.py", line 194, in send_email_task
    send_mail(
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/smtplib.py", line 882, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 5b1f17b1804b1-4365d116d8fsm572848555e9.17 - gsmtp', 'explorebg.quiz@outlook.com')

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:22:39
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x105c05d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 11:22:39,523: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:22:39,528: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:22:39,528: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:22:39,530: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:22:40,543: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:22:40,543: INFO/MainProcess] mingle: all alone
[2025-01-06 11:22:40,551: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:30:07
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x102216d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 11:30:07,730: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:30:07,734: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:30:07,735: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:30:07,735: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:30:08,747: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:30:08,747: INFO/MainProcess] mingle: all alone
[2025-01-06 11:30:08,757: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:37:32
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x104045d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 11:37:32,956: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:37:32,961: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:37:32,962: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:37:32,964: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:37:33,976: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:37:33,977: INFO/MainProcess] mingle: all alone
[2025-01-06 11:37:33,985: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:44:38
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x10595dd00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 11:44:38,830: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:44:38,835: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:44:38,835: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:44:38,838: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:44:39,849: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:44:39,849: INFO/MainProcess] mingle: all alone
[2025-01-06 11:44:39,856: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:47:58
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x104005d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 11:47:58,511: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:47:58,516: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:47:58,516: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:47:58,518: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:47:59,532: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:47:59,532: INFO/MainProcess] mingle: all alone
[2025-01-06 11:47:59,542: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.
[2025-01-06 11:48:21,872: INFO/MainProcess] Task explorebg.questions.views.send_email_task[25517f6d-0532-451c-b3a3-44fd3fdacbff] received
[2025-01-06 11:48:21,879: WARNING/ForkPoolWorker-8] +++++++++++++++++++++++EMAIL SEND+++++++++++++++++++++++++++
[2025-01-06 11:48:22,430: ERROR/ForkPoolWorker-8] Task explorebg.questions.views.send_email_task[25517f6d-0532-451c-b3a3-44fd3fdacbff] raised unexpected: SMTPSenderRefused(530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-38a1c847263sm47470788f8f.50 - gsmtp', 'explorebg.quiz@outlook.com')
Traceback (most recent call last):
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/explorebg/questions/views.py", line 194, in send_email_task
    send_mail(
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/smtplib.py", line 882, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-38a1c847263sm47470788f8f.50 - gsmtp', 'explorebg.quiz@outlook.com')

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 11:50:35
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x101c39d00
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-06 11:50:35,337: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:50:35,343: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 11:50:35,344: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 11:50:35,346: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 11:50:36,359: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 11:50:36,359: INFO/MainProcess] mingle: all alone
[2025-01-06 11:50:36,367: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 12:31:27
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1045f3100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-06 12:31:27,579: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 12:31:27,584: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 12:31:27,584: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 12:31:27,587: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 12:31:28,599: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 12:31:28,599: INFO/MainProcess] mingle: all alone
[2025-01-06 12:31:28,607: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.
[2025-01-06 12:31:49,639: INFO/MainProcess] Task explorebg.questions.tasks.send_email_task[def5fdef-7679-4408-b4bf-90d6254a6155] received
[2025-01-06 12:31:49,644: WARNING/ForkPoolWorker-8] +++++++++++++++++++++++EMAIL SEND+++++++++++++++++++++++++++
[2025-01-06 12:31:50,834: INFO/ForkPoolWorker-8] Task explorebg.questions.tasks.send_email_task[def5fdef-7679-4408-b4bf-90d6254a6155] succeeded in 1.1918596669999992s: None

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-06 12:33:22
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x106deb100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task
  . explorebg.questions.views.send_email_task

[2025-01-06 12:33:22,421: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 12:33:22,430: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-06 12:33:22,431: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-06 12:33:22,432: INFO/MainProcess] mingle: searching for neighbors
[2025-01-06 12:33:23,443: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-06 12:33:23,443: INFO/MainProcess] mingle: all alone
[2025-01-06 12:33:23,452: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.
[2025-01-06 12:33:48,669: INFO/MainProcess] Task explorebg.questions.views.send_email_task[fb2435f9-a166-4b02-b293-0254b5e2cafd] received
[2025-01-06 12:33:48,671: WARNING/ForkPoolWorker-8] +++++++++++++++++++++++EMAIL SEND+++++++++++++++++++++++++++
[2025-01-06 12:33:49,843: INFO/ForkPoolWorker-8] Task explorebg.questions.views.send_email_task[fb2435f9-a166-4b02-b293-0254b5e2cafd] succeeded in 1.1732044170000009s: None

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-07 20:00:54
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x101a53100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-07 20:00:55,091: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-07 20:00:55,099: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-07 20:00:55,100: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-07 20:00:55,101: INFO/MainProcess] mingle: searching for neighbors
[2025-01-07 20:00:56,124: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-07 20:00:56,124: INFO/MainProcess] mingle: all alone
[2025-01-07 20:00:56,136: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

SIGHUP not supported: Restarting with SIGHUP is unstable on this platform!
[2025-01-07 20:08:55,409: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:56501 exited with 'exitcode 70'
[2025-01-07 20:08:55,474: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:56508 exited with 'exitcode 70'
[2025-01-07 20:08:55,485: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:56507 exited with 'exitcode 70'
[2025-01-07 20:08:55,497: ERROR/MainProcess] Process 'ForkPoolWorker-6' pid:56506 exited with 'exitcode 70'
[2025-01-07 20:08:55,508: ERROR/MainProcess] Process 'ForkPoolWorker-5' pid:56505 exited with 'exitcode 70'
[2025-01-07 20:08:55,520: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:56504 exited with 'exitcode 70'
[2025-01-07 20:08:55,531: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:56503 exited with 'exitcode 70'
[2025-01-07 20:08:55,542: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:56502 exited with 'exitcode 70'
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-09 14:44:09
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x102773100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-09 14:44:09,842: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 14:44:09,849: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-09 14:44:09,850: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 14:44:09,851: INFO/MainProcess] mingle: searching for neighbors
[2025-01-09 14:44:10,866: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-09 14:44:10,866: INFO/MainProcess] mingle: all alone
[2025-01-09 14:44:10,875: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-09 14:57:13
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x10392b100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-09 14:57:14,281: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 14:57:14,289: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-09 14:57:14,290: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 14:57:14,291: INFO/MainProcess] mingle: searching for neighbors
[2025-01-09 14:57:15,304: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-09 14:57:15,304: INFO/MainProcess] mingle: all alone
[2025-01-09 14:57:15,314: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-09 15:01:34
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1053eb100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-09 15:01:34,457: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 15:01:34,463: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-09 15:01:34,464: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 15:01:34,465: INFO/MainProcess] mingle: searching for neighbors
[2025-01-09 15:01:35,493: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-09 15:01:35,494: INFO/MainProcess] mingle: all alone
[2025-01-09 15:01:35,508: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-09 15:03:46
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1017c7100
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-09 15:03:46,788: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 15:03:46,795: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-09 15:03:46,796: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-09 15:03:46,797: INFO/MainProcess] mingle: searching for neighbors
[2025-01-09 15:03:47,813: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@Borislavs-MacBook-Air.local.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(

[2025-01-09 15:03:47,814: INFO/MainProcess] mingle: all alone
[2025-01-09 15:03:47,823: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-12 18:14:17
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x103fd03d0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-12 18:14:18,102: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 18:14:18,108: INFO/MainProcess] Connected to redis://localhost:6379/0
[2025-01-12 18:14:18,109: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 18:14:18,110: INFO/MainProcess] mingle: searching for neighbors
[2025-01-12 18:14:19,116: INFO/MainProcess] mingle: all alone
[2025-01-12 18:14:19,127: INFO/MainProcess] celery@Borislavs-MacBook-Air.local ready.
[2025-01-12 18:14:57,987: INFO/MainProcess] Task explorebg.questions.tasks.send_email_task[6f094f37-3511-4452-827d-5ba6cc459242] received
[2025-01-12 18:15:00,943: INFO/ForkPoolWorker-8] Task explorebg.questions.tasks.send_email_task[6f094f37-3511-4452-827d-5ba6cc459242] succeeded in 2.9538667079999996s: None

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-12 18:34:32
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x105fe03d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-12 18:34:32,507: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 18:34:32,521: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-12 18:34:34,532: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-12 18:34:38,545: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-12 18:34:44,574: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-12 18:34:52,593: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-12 18:35:02,630: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-12 18:35:14,673: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-12 18:35:28,726: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-12 18:35:44,784: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-12 18:36:02,844: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-12 18:36:22,912: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-12 18:36:44,976: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-12 18:37:09,064: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)

[2025-01-12 18:37:35,160: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 28.00 seconds... (14/100)

[2025-01-12 18:38:03,258: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 30.00 seconds... (15/100)

[2025-01-12 18:38:33,351: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:39:05,466: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:39:37,591: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:40:09,704: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:40:41,809: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:41:13,925: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:41:46,033: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:42:18,137: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:42:50,251: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:43:22,377: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-12 18:43:54,483: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-12 18:44:09
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1090bc3d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379/0
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/1
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-12 18:44:10,164: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 18:44:10,174: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-12 18:44:12,187: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-12 18:44:16,196: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-12 18:44:22,224: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-12 18:44:30,259: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-12 18:44:40,290: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-12 18:44:52,329: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-12 18:45:06,376: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-12 18:45:22,429: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-12 18:45:40,482: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-12 18:46:00,554: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-12 18:46:22,622: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379/0: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-12 20:22:43
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1042903d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-12 20:22:44,091: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 20:22:44,097: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-12 20:22:46,112: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-12 20:22:50,132: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-12 20:22:56,167: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-12 20:23:04,203: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-12 20:23:14,240: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-12 22:11:09
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1047383d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-12 22:11:10,072: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 22:11:10,076: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-12 22:11:12,091: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-12 22:11:16,119: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-12 22:11:22,152: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-12 22:11:30,189: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-12 22:11:40,242: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-12 22:11:52,293: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-12 22:12:06,355: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-12 22:12:22,427: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-12 22:12:40,514: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-12 22:13:00,594: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-12 22:13:22,674: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-12 22:13:46,770: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)

[2025-01-12 22:14:12,881: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 28.00 seconds... (14/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-12 22:14:42
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1041083d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-12 22:14:42,290: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-12 22:14:42,295: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-12 22:14:44,307: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-12 22:14:48,324: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-12 22:14:54,347: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-12 22:15:02,378: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-12 22:15:12,434: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-12 22:15:24,475: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-12 22:15:38,547: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-12 22:15:54,600: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-12 22:16:12,669: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-12 22:16:32,753: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-12 22:16:54,839: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-12 22:17:18,942: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)

[2025-01-12 22:17:45,043: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 28.00 seconds... (14/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 08:20:47
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1023783d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 08:20:47,948: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 08:20:47,953: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 08:20:49,962: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 08:20:53,975: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 08:20:59,998: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 08:21:08,027: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 08:21:18,069: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 08:21:30,126: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 08:21:44,173: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 08:22:00,233: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 08:22:18,305: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-13 08:22:38,388: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-13 08:23:00,469: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-13 08:23:24,552: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)

[2025-01-13 08:23:50,650: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 28.00 seconds... (14/100)

[2025-01-13 08:24:18,773: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 30.00 seconds... (15/100)

[2025-01-13 08:24:48,865: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-13 08:25:20,995: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-13 08:25:53,125: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-13 08:26:25,259: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-13 08:26:57,401: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)

[2025-01-13 08:27:29,521: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 32.00 seconds... (16/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 08:27:59
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1077243d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 08:27:59,493: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 08:27:59,498: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 08:28:01,511: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 08:28:05,535: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 08:28:11,562: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 08:28:19,596: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 08:28:29,647: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 08:28:41,705: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 08:28:55,765: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 08:29:11,825: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 08:29:29,899: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-13 08:29:49,982: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-13 08:30:12,066: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:13:19
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1018743d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:13:19,729: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:13:19,734: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:13:21,748: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:13:25,764: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:13:31,793: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:13:39,827: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 11:13:49,869: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 11:14:01,923: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 11:14:15,972: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 11:14:32,042: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:14:45
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x101c883d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:14:46,067: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:14:46,072: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:14:48,086: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:14:52,102: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:14:58,132: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:16:10
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1059ac3d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:16:10,297: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:16:10,303: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:16:12,317: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:16:16,335: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:16:22,359: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:16:30,393: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 11:16:40,440: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:20:54
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1062b83d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:20:55,207: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:20:55,214: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:20:57,228: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:21:01,251: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:21:07,280: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:21:15,313: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:22:22
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x101e103d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:22:22,406: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:22:22,411: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:22:24,427: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:22:28,440: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:22:34,466: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:22:42,505: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 11:22:52,550: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 11:23:04,607: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 11:23:18,665: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 11:23:34,738: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 11:23:52,824: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:25:24
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1058903d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:25:25,082: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:25:25,087: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:25:27,099: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:25:31,123: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:25:37,154: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:26:02
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1065643d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:26:03,147: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:26:03,154: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:26:05,170: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:26:09,196: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:26:15,230: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:26:23,276: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 11:26:33,327: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 11:26:45,379: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 11:26:59,451: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 11:27:15,522: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 11:27:33,614: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-13 11:27:53,700: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:28:13
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1020503d0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:28:13,452: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:28:13,458: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:28:15,471: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:28:19,491: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:28:25,528: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:28:33,562: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 11:28:43,613: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 11:28:55,652: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 11:29:09,725: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 11:29:25,794: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 11:29:43,874: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 11:32:04
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x10584ab80
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 11:32:05,110: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 11:32:05,117: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 11:32:07,133: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 11:32:11,149: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 11:32:17,179: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 11:32:25,217: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 11:32:35,261: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 11:32:47,310: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 11:33:01,368: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 11:33:17,441: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 11:33:35,519: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-13 11:33:55,601: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-13 11:34:17,679: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-13 11:34:41,785: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)

[2025-01-13 11:35:07,887: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 28.00 seconds... (14/100)

[2025-01-13 11:35:35,992: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 30.00 seconds... (15/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-13 17:50:45
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x101da1df0
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-13 17:50:45,307: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-13 17:50:45,312: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-13 17:50:47,321: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-13 17:50:51,342: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-13 17:50:57,372: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-13 17:51:05,399: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-13 17:51:15,445: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-13 17:51:27,493: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-13 17:51:41,554: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-13 17:51:57,621: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-13 17:52:15,701: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-13 17:52:35,785: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-13 17:52:57,895: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-13 17:53:22,014: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-18 15:02:20
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x1040e6b80
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-18 15:02:20,938: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-18 15:02:20,952: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-18 15:02:22,961: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-18 15:02:26,980: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-18 15:02:33,006: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-18 15:02:41,046: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-18 15:02:51,081: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-18 15:03:03,124: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-18 15:03:17,177: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-18 15:03:33,232: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
Traceback (most recent call last):
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/bin/worker.py", line 348, in worker
    worker = app.Worker(
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/worker.py", line 93, in __init__
    self.app.loader.init_worker()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/loaders/base.py", line 110, in init_worker
    self.import_default_modules()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/loaders/base.py", line 104, in import_default_modules
    raise response
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/fixups/django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/fixups/django.py", line 140, in validate_models
    run_checks()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 446, in check
    for pattern in self.url_patterns:
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 632, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 625, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/borislavvoytash/Desktop/Explore/Quiz-Application/explorebg/urls.py", line 14, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
IndexError: list index out of range
 
 -------------- celery@Borislavs-MacBook-Air.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-15.2-arm64-arm-64bit 2025-01-18 15:06:15
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         explorebg:0x10706ab80
- ** ---------- .> transport:   redis://red-cu20jqlsvqrc73f16n70:6379//
- ** ---------- .> results:     redis://red-cu20jqlsvqrc73f16n70:6379/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . explorebg.questions.tasks.send_email_task

[2025-01-18 15:06:16,052: WARNING/MainProcess] /Users/borislavvoytash/Desktop/Explore/Quiz-Application/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2025-01-18 15:06:16,057: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 2.00 seconds... (1/100)

[2025-01-18 15:06:18,071: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 4.00 seconds... (2/100)

[2025-01-18 15:06:22,087: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 6.00 seconds... (3/100)

[2025-01-18 15:06:28,111: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 8.00 seconds... (4/100)

[2025-01-18 15:06:36,150: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 10.00 seconds... (5/100)

[2025-01-18 15:06:46,191: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 12.00 seconds... (6/100)

[2025-01-18 15:06:58,237: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 14.00 seconds... (7/100)

[2025-01-18 15:07:12,279: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 16.00 seconds... (8/100)

[2025-01-18 15:07:28,339: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 18.00 seconds... (9/100)

[2025-01-18 15:07:46,390: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 20.00 seconds... (10/100)

[2025-01-18 15:08:06,457: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 22.00 seconds... (11/100)

[2025-01-18 15:08:28,538: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 24.00 seconds... (12/100)

[2025-01-18 15:08:52,622: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 26.00 seconds... (13/100)

[2025-01-18 15:09:18,709: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 28.00 seconds... (14/100)

[2025-01-18 15:09:46,801: ERROR/MainProcess] consumer: Cannot connect to redis://red-cu20jqlsvqrc73f16n70:6379//: Error 8 connecting to red-cu20jqlsvqrc73f16n70:6379. nodename nor servname provided, or not known..
Trying again in 30.00 seconds... (15/100)


worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
